### ISSUE TITLE
Unable to upload instance image for demo

### ISSUE THREAD

**Issue by ghost** [r-eifler/IPEXCO-frontend#69]
Uploading an image (.png&.jpg) to a demo is not successful. It fails with status code 500 upon selecting the image.

**Comment by r-eifler** [comment]
@guka00001 The image is automatically uploaded when you select it. Are you sure that you have write access to the folder you mounted as a volume for the backend constainer?

**Comment by r-eifler** [comment]
I found another problem that could cause this issue.

**Comment by r-eifler** [comment]
@guka00001 This problem should be fixed with the fix for issue 77. If it now works for you please close this issue, otherwise please let me know  what error exactly you are getting.

**Comment by ghost** [comment]
@r-eifler 
It is still not working. I have the correct access rights. I tested on my local environment for now. Here are the logs from the ipexco container


GET /api/project/67fad44cb2b92c70e2db6663 304 10.526 ms - -
GET /api/domain-spec/67f551508b76462f99c54ab0 304 10.436 ms - -
GET /api/plan-property/?projectId=67fad44cb2b92c70e2db6663 304 10.854 ms - -
GET /api/demo/?projectId=67fad44cb2b92c70e2db6663 304 11.170 ms - -
GET /api/plan-property/?projectId=67fbc758aef18fd6202a19dd 304 5.678 ms - -
GET /api/plan-property/?projectId=67ff71f5a8ec79e21b968afb 304 5.288 ms - -
POST /api/demo/image 500 26.127 ms - 130

**Comment by r-eifler** [comment]
@guka00001 can you please pull the backend dev branch again and check whether it works now.

**Comment by ghost** [comment]
@r-eifler I am running the backend as docker. I did not succeed in running it natively. Can I just pull the image again?

**Comment by r-eifler** [comment]
@guka00001 You never mentioned that you managed to run the backend with docker.  No I haven't built a new docker image yet since last time we spoke you had abandoned this option. I will notify you when you can pull a new image.

**Comment by ghost** [comment]
@r-eifler The notice about me successfully running the entire setup for IPEXCO last week Tuesday was referring to running all docker images.
